package cpu

import "fmt"

type Decoded struct {
	*Operation
	Addressing
}

var OpecodeMapping []Decoded

func (c *Cpu) initDecoder() {

	OpecodeMapping = []Decoded{
		// 0x
		{Brk, Implicit},
		{Ora, IndirectX},
		{nil, nil},
		{Slo, IndirectX},
		{Nop, ZeroPage},
		{Ora, ZeroPage},
		{Asl, ZeroPage},
		{Slo, ZeroPage},

		{Php, Implicit},
		{Ora, Immediate},
		{Asl, Implicit},
		{Anc, Immediate},
		{Nop, Absolute},
		{Ora, Absolute},
		{Asl, Absolute},
		{Slo, Absolute},
		// 1x
		{Bpl, Relative},
		{Ora, IndirectY},
		{nil, nil},
		{Slo, IndirectY},
		{Nop, ZeroPageX},
		{Ora, ZeroPageX},
		{Asl, ZeroPageX},
		{Slo, ZeroPageX},

		{Clc, Implicit},
		{Ora, AbsoluteY},
		{Nop, Implicit},
		{Slo, AbsoluteY},
		{Nop, AbsoluteX},
		{Ora, AbsoluteX},
		{Asl, AbsoluteX},
		{Slo, AbsoluteX},
		// 2x
		{Jsr, Absolute},
		{And, IndirectX},
		{nil, nil},
		{Rla, IndirectX},
		{Bit, ZeroPage},
		{And, ZeroPage},
		{Rol, ZeroPage},
		{Rla, ZeroPage},

		{Plp, Implicit},
		{And, Immediate},
		{Rol, Implicit},
		{Anc, Immediate},
		{Bit, Absolute},
		{And, Absolute},
		{Rol, Absolute},
		{Rla, Absolute},
		// 3x
		{Bmi, Relative},
		{And, IndirectY},
		{nil, nil},
		{Rla, IndirectY},
		{Nop, ZeroPageX},
		{And, ZeroPageX},
		{Rol, ZeroPageX},
		{Rla, ZeroPageX},

		{Sec, Implicit},
		{And, AbsoluteY},
		{Nop, Implicit},
		{Rla, AbsoluteY},
		{Nop, AbsoluteX},
		{And, AbsoluteX},
		{Rol, AbsoluteX},
		{Rla, AbsoluteX},
		// 4x
		{Rti, Implicit},
		{Eor, IndirectX},
		{nil, nil},
		{Sre, IndirectX},
		{Nop, ZeroPage},
		{Eor, ZeroPage},
		{Lsr, ZeroPage},
		{Sre, ZeroPage},

		{Pha, Implicit},
		{Eor, Immediate},
		{Lsr, Implicit},
		{Alr, Immediate},
		{Jmp, Absolute},
		{Eor, Absolute},
		{Lsr, Absolute},
		{Sre, Absolute},
		// 5x
		{Bvc, Relative},
		{Eor, IndirectY},
		{nil, nil},
		{Sre, IndirectY},
		{Nop, ZeroPageX},
		{Eor, ZeroPageX},
		{Lsr, ZeroPageX},
		{Sre, ZeroPageX},

		{Cli, Implicit},
		{Eor, AbsoluteY},
		{Nop, Implicit},
		{Sre, AbsoluteY},
		{Nop, AbsoluteX},
		{Eor, AbsoluteX},
		{Lsr, AbsoluteX},
		{Sre, AbsoluteX},
		// 6x
		{Rts, Implicit},
		{Adc, IndirectX},
		{nil, nil},
		{Rra, IndirectX},
		{Nop, IndirectX},
		{Adc, ZeroPage},
		{Ror, ZeroPage},
		{Rra, ZeroPage},

		{Pla, Implicit},
		{Adc, Immediate},
		{Ror, Implicit},
		{Arr, Immediate},
		{Jmp, Indirect},
		{Adc, Absolute},
		{Ror, Absolute},
		{Rra, Absolute},
		// 7x
		{Bvs, Relative},
		{Adc, IndirectY},
		{nil, nil},
		{Rra, IndirectY},
		{Nop, ZeroPageX},
		{Adc, ZeroPageX},
		{Ror, ZeroPageX},
		{Rra, ZeroPageX},

		{Sei, Implicit},
		{Adc, AbsoluteY},
		{Nop, Implicit},
		{Rra, AbsoluteY},
		{Nop, AbsoluteX},
		{Adc, AbsoluteX},
		{Ror, AbsoluteX},
		{Rra, AbsoluteX},
		// 8x
		{Nop, Immediate},
		{Sta, IndirectX},
		{Nop, Immediate},
		{Sax, IndirectX},
		{Sty, ZeroPage},
		{Sta, ZeroPage},
		{Stx, ZeroPage},
		{Sax, ZeroPage},

		{Dey, Implicit},
		{Nop, Immediate},
		{Txa, Implicit},
		{Xaa, Immediate},
		{Sty, Absolute},
		{Sta, Absolute},
		{Stx, Absolute},
		{Sax, Absolute},
		// 9x
		{Bcc, Relative},
		{Sta, IndirectY},
		{nil, nil},
		{Ahx, IndirectY},
		{Sty, ZeroPageX},
		{Sta, ZeroPageX},
		{Stx, ZeroPageY},
		{Sax, ZeroPageY},

		{Tya, Implicit},
		{Sta, AbsoluteY},
		{Txs, Implicit},
		{Tas, AbsoluteY},
		{Shy, AbsoluteX},
		{Sta, AbsoluteX},
		{Shx, AbsoluteY},
		{Ahx, AbsoluteY},
		// Ax
		{Ldy, Immediate},
		{Lda, IndirectX},
		{Ldx, Immediate},
		{Lax, IndirectX},
		{Ldy, ZeroPage},
		{Lda, ZeroPage},
		{Ldx, ZeroPage},
		{Lax, ZeroPage},

		{Tay, Implicit},
		{Lda, Immediate},
		{Tax, Implicit},
		{Lax, Immediate},
		{Ldy, Absolute},
		{Lda, Absolute},
		{Ldx, Absolute},
		{Lax, Absolute},
		// Bx
		{Bcs, Relative},
		{Lda, IndirectY},
		{nil, nil},
		{Lax, IndirectY},
		{Ldy, ZeroPageX},
		{Lda, ZeroPageX},
		{Ldx, ZeroPageY},
		{Lax, ZeroPageY},

		{Clv, Implicit},
		{Lda, AbsoluteY},
		{Tsx, Implicit},
		{Las, AbsoluteY},
		{Ldy, AbsoluteX},
		{Lda, AbsoluteX},
		{Ldx, AbsoluteY},
		{Lax, AbsoluteY},
		// Cx
		{Cpy, Immediate},
		{Cmp, IndirectX},
		{Nop, Immediate},
		{Dcp, IndirectX},
		{Cpy, ZeroPage},
		{Cmp, ZeroPage},
		{Dec, ZeroPage},
		{Dcp, ZeroPage},

		{Iny, Implicit},
		{Cmp, Immediate},
		{Dex, Implicit},
		{Axs, Immediate},
		{Cpy, Absolute},
		{Cmp, Absolute},
		{Dec, Absolute},
		{Dcp, Absolute},
		// Dx
		{Bne, Relative},
		{Cmp, IndirectY},
		{nil, nil},
		{Dcp, IndirectY},
		{Nop, ZeroPageX},
		{Cmp, ZeroPageX},
		{Dec, ZeroPageX},
		{Dcp, ZeroPageX},

		{Cld, Implicit},
		{Cmp, AbsoluteY},
		{Nop, Implicit},
		{Dcp, AbsoluteY},
		{Nop, AbsoluteX},
		{Cmp, AbsoluteX},
		{Dec, AbsoluteX},
		{Dcp, AbsoluteX},
		// Ex
		{Cpx, Immediate},
		{Sbc, IndirectX},
		{Nop, Immediate},
		{Isc, IndirectX},
		{Cpx, ZeroPage},
		{Sbc, ZeroPage},
		{Inc, ZeroPage},
		{Isc, ZeroPage},

		{Inx, Implicit},
		{Sbc, Immediate},
		{Nop, Implicit},
		{Sbc, Immediate},
		{Cpx, Absolute},
		{Sbc, Absolute},
		{Inc, Absolute},
		{Isc, Absolute},
		// Fx
		{Beq, Relative},
		{Sbc, IndirectY},
		{nil, nil},
		{Isc, IndirectY},
		{Nop, ZeroPageX},
		{Sbc, ZeroPageX},
		{Inc, ZeroPageX},
		{Isc, ZeroPageX},

		{Sed, Implicit},
		{Sbc, AbsoluteY},
		{Nop, Implicit},
		{Isc, AbsoluteY},
		{Nop, AbsoluteX},
		{Sbc, AbsoluteX},
		{Inc, AbsoluteX},
		{Isc, AbsoluteX},
	}
}
func (c *Cpu) decode() {
	decoded := OpecodeMapping[c.instructionOpecode]
	c.op = decoded.Operation
	c.mode = decoded.Addressing
	if c.op == nil || c.mode == nil {
		panic(fmt.Sprintf("invalid opecode %v", c.instructionOpecode))
	}

}
